### ISSUE TITLE
Data-set: Sites representative of popular JavaScript loading patterns

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/discovery#3]
Requirements:

- Ordered by Alexa ranking
- Optionally use Webpack (check Webpack JSON signature)
- Optionally look at RequireJS usage. Is code bundled with it still being deployed?
- Optionally use Browserify (separate run)
- Have first-party JS where they're shipping more than 1 x JS file (separate run)

Who wanted this?
V8

**Comment by addyosmani** [comment]
Sites using Webpack in the top 500K that include `webpackPolyfill` in their request bodies (note, this does not distinguish between sites pulling in Webpack bundled code from third parties)

https://storage.googleapis.com/addyosmani/webpack-sites.csv

Consumers can just trim down to the number they need. This is Alexa ranked as needed.

**Update with Rick's first party pattern from lower down:**

```SQL
SELECT
  runs.rank,
  har.domain
FROM (
  SELECT
    NET.REG_DOMAIN(page) AS domain,
    page
  FROM
    httparchive.har.2017_07_15_chrome_requests_bodies
  WHERE
    REGEXP_CONTAINS(body, r'webpackPolyfill')
    AND NET.REG_DOMAIN(page) = NET.REG_DOMAIN(url)
  GROUP BY
    domain,
    page) AS har
INNER JOIN (
  SELECT
    rank,
    url
  FROM
    httparchive.runs.2017_07_15_pages) AS runs
ON
  runs.url = har.page
ORDER BY
  rank ASC
```

~7728 sites including Tumblr, Nike, Nintendo.

**Comment by igrigorik** [comment]
@addyosmani do you have the accompanying query for this? Would love to have this documented. 

As an aside, https://discuss.httparchive.org/ is a good place to share findings, queries, etc. :)

**Comment by addyosmani** [comment]
@igrigorik I do! I feel bad sharing it as I'm sure it can be heavily improved :)

```SQL
SELECT
  t2.Alexa_rank,
  t1.*
FROM (
  SELECT
    NET.REG_DOMAIN(page) AS Domain,
    ANY_VALUE(NET.HOST(page)) AS Host
  FROM
    `httparchive.har.2017_07_01_chrome_requests_bodies`
  WHERE
    REGEXP_CONTAINS(body, r'webpackPolyfill')
  GROUP BY
    Domain ) t1
LEFT JOIN
  `httparchive.urls.20170315` t2
ON
  t1.Domain = t2.Alexa_domain
ORDER BY
  CASE
    WHEN t2.Alexa_rank IS NULL THEN 1
    ELSE 0 END,
  t2.Alexa_rank
```

> As an aside, https://discuss.httparchive.org/ is a good place to share findings, queries, etc. :)

I'll keep that in mind! That's probably also a good place to sanity check some the queries I'm running.

*For historic context, I also looked at `window.webpackJsonp=function` as a signature, but Sean Larkin from Webpack suggested the polyfill would be more accurate to search for*

**Comment by igrigorik** [comment]
> I feel bad sharing it as I'm sure it can be heavily improved :)

You've just described every query I've ever shared.. ;-)

> For historic context, I also looked at window.webpackJsonp=function as a signature, but Sean Larkin from Webpack suggested the polyfill would be more accurate to search for

Interesting. Note that we can also add "[custom metrics](https://github.com/HTTPArchive/httparchive/tree/master/custom_metrics)", which can be run at the end of the page load -- this gives you access to DOM, etc. The "only" downside is that you can't apply them retroactively.

/cc @rviscomi

**Comment by addyosmani** [comment]
Another one. RequireJS usage still in the wild:

**Updated to use Rick's version with 1st party focus**

```SQL
SELECT
  runs.rank,
  har.domain
FROM (
  SELECT
    NET.REG_DOMAIN(page) AS domain,
    page
  FROM
    httparchive.har.2017_07_15_chrome_requests_bodies
  WHERE
    REGEXP_CONTAINS(body, r'requirejs\(')
    AND NET.REG_DOMAIN(page) = NET.REG_DOMAIN(url)
  GROUP BY
    domain,
    page) AS har
INNER JOIN (
  SELECT
    rank,
    url
  FROM
    httparchive.runs.2017_07_15_pages) AS runs
ON
  runs.url = har.page
ORDER BY
  rank ASC
```

Looking at about ~1K sites, some well known ones in there include Slate and Victoria's Secret.

https://storage.googleapis.com/addyosmani/requirejs.csv

Digging in deeper a lot of this appears to be legacy code or pipelines still relying on older bundler tooling.

**Comment by addyosmani** [comment]
@rviscomi @igrigorik Is there a good way to limit the domains returned such that a match against the request bodies (for a string) must also be on the same origin as that domain? i.e first-party only code. 

I have a feeling some of these numbers are a little inflated as video players, widgets etc. are also being counted.

**Comment by rviscomi** [comment]
Regarding first-party only, you could compare the domain of the page to the domain of the resource URL:

```sql
SELECT
  NET.REG_DOMAIN(page) AS domain
FROM
  httparchive.har.2017_07_15_chrome_requests_bodies
WHERE
  REGEXP_CONTAINS(body, r'requirejs\(')
  AND NET.REG_DOMAIN(page) = NET.REG_DOMAIN(url)
GROUP BY
  domain
```

And same thing with ranking:

```sql
SELECT
  runs.rank,
  har.domain
FROM (
  SELECT
    NET.REG_DOMAIN(page) AS domain,
    page
  FROM
    httparchive.har.2017_07_15_chrome_requests_bodies
  WHERE
    REGEXP_CONTAINS(body, r'requirejs\(')
    AND NET.REG_DOMAIN(page) = NET.REG_DOMAIN(url)
  GROUP BY
    domain,
    page) AS har
INNER JOIN (
  SELECT
    rank,
    url
  FROM
    httparchive.runs.2017_07_15_pages) AS runs
ON
  runs.url = har.page
ORDER BY
  rank ASC
```

**Comment by addyosmani** [comment]
Thanks, Rick! I've applied that to some of the earlier runs and am seeing more realistic numbers in there.
